---
# Title: role-nextcloud-server
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/20.04/nexcloud-code.yml
#
# Description:
#   Role for deploy a Nextcloud server.

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C54D189F4BA284D

- name: "Install repository"
  apt_repository:
    repo: deb https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004 ./
    state: present

- name: "Install packages"
  apt:
    pkg:
    - loolwsd 
    - code-brand
    
