---
# Title: role-nextcloud-server
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/main.yml
#
# Description:
#   Role for deploy a Nextcloud server.

- name: "For OS: Ubuntu 20.04LTS, Arch: amd64"
  import_tasks: 20.04/nextcloud-base.yml
  when:
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"

- name: "For OS: Ubuntu 20.04LTS, Arch: amd64"
  import_tasks: 20.04/redis-server.yml
  when:
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"
